[package]
name = "consts"
version = "0.1.0-alpha"
authors = ["Nanai10a"]
edition = "2018"
description = "making `const` strings easier!"

readme = "README.md"
homepage = ""
repository = "https://github.com/Nanai10a/consts"
license-file = "LICENSE"

keywords = []
categories = []
publish = false
